# Step 1: Define an algorithm in pseudocode as comments [cite: 40]
# Algorithm to find the Largest number in a List [cite: 41]
# 1. Assume the first number is the Largest [cite: 42]
# 2. Compare each number with the current Largest [cite: 43]
# 3. If a number is Larger, update the Largest [cite: 44]
# 4. Return the largest number [cite: 45]

# Step 2: Implement it in Python
numbers = [10, 5, 20, 8, 15]
largest = numbers[0]
for num in numbers:
    if num > largest:
        largest = num
print("Largest number:", largest)
# Step 1: Define a simple Linear Loop [cite: 56]
def print_items(items):
    for item in items:
        print(item)

# Step 2: Observe operations relative to input size [cite: 60]
sample = list(range(100))  # [cite: 61]
print_items(sample) # O(n) [cite: 62]
# Step 1: Implement Linear search [cite: 70]
def linear_search(arr, target):  # [cite: 71]
    for i in range(len(arr)):  # [cite: 71]
        if arr[i] == target:  # [cite: 72]
            return i  # [cite: 73]
    return -1  # [cite: 74]

# Step 2: Call the function [cite: 75]
data = [3, 5, 2, 4, 9]  # [cite: 76]
index = linear_search(data, 4)  # [cite: 77]
print("Found at index:", index)  # [cite: 78]
# Step 1: Implement binary search [cite: 82]
def binary_search(arr, target):  # [cite: 83]
    low = 0  # [cite: 84]
    high = len(arr) - 1  # [cite: 86]

    while low <= high:  # [cite: 87]
        mid = (low + high) // 2  # [cite: 89]
        if arr[mid] == target:  # [cite: 90]
            return mid  # [cite: 91]
        elif arr[mid] < target:  # [cite: 92]
            low = mid + 1  # [cite: 94]
        else:  # [cite: 93]
            high = mid - 1  # [cite: 95]
    return -1  # [cite: 96]

# Step 2: Test with a sorted List [cite: 98]
sorted_data = [1, 3, 5, 7, 9, 11]  # [cite: 99]
result = binary_search(sorted_data, 7)  # [cite: 100]
print("Found at index:", result)  # [cite: 101]
# Step 1: Implement bubble sort [cite: 105]
def bubble_sort(arr):  # [cite: 106]
    n = len(arr)  # [cite: 107]
    for i in range(n):  # [cite: 108]
        for j in range(0, n - i - 1):  # [cite: 109, 167]
            if arr[j] > arr[j + 1]:  # [cite: 110]
                arr[j], arr[j + 1] = arr[j + 1], arr[j]  # [cite: 112]

# Step 2: Test sorting [cite: 113]
to_sort = [64, 34, 25, 12, 22, 11, 90]  # [cite: 114]
bubble_sort(to_sort)  # [cite: 115]
print("Sorted list:", to_sort)  # [cite: 116]
# Step 1: Implement selection sort [cite: 123]
def selection_sort(arr):  # [cite: 123]
    for i in range(len(arr)):  # [cite: 124]
        min_idx = i  # [cite: 124]
        for j in range(i + 1, len(arr)):  # [cite: 125, 126]
            if arr[j] < arr[min_idx]:  # [cite: 127]
                min_idx = j  # [cite: 128]
        arr[i], arr[min_idx] = arr[min_idx], arr[i]  # [cite: 129]

# Step 2: Test and observe performance [cite: 130]
sample_data = [29, 10, 14, 37, 13]  # [cite: 131]
selection_sort(sample_data)  # [cite: 132]
print("Sorted List:", sample_data)  # [cite: 133]
# Step 1: Implement insertion sort [cite: 137]
def insertion_sort(arr):  # [cite: 138]
    for i in range(1, len(arr)):  # [cite: 139]
        key = arr[i]  # [cite: 140]
        j = i - 1  # [cite: 141]
        while j >= 0 and key < arr[j]:  # [cite: 142, 143]
            arr[j + 1] = arr[j]  # [cite: 144, 145]
            j -= 1  # [cite: 146]
        arr[j + 1] = key  # [cite: 147]

# Step 2: Test and measure performance [cite: 148]
arr = [12, 11, 13, 5, 6] [cite: 149]
insertion_sort(arr)  # [cite: 150]
print("Sorted array:", arr)  # [cite: 151]
import time  # [cite: 155]
import random  # [cite: 156]

# Step 1: Generate sample data [cite: 157]
data = random.sample(range(100000), 10000) [cite: 158]

# Step 2: Measure Python's built-in sort (Timsort, O(n log n)) [cite: 159, 161]
start = time.time() [cite: 160]
sorted_data = sorted(data) [cite: 161]
print("Built-in sort time:", time.time() - start) [cite: 162]

# Step 3: Bubble sort demonstration [cite: 163]
# Note: For 10,000 items, Bubble Sort is intentionally slow [cite: 163, 171]